# Generated by Django 2.0.5 on 2018-09-04 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_descriptive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_description',
            field=models.CharField(max_length=400),
        ),
    ]
