# Generated by Django 2.0.5 on 2018-09-05 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180904_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descriptive',
            name='question',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_description',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Descriptive',
        ),
    ]
