# Generated by Django 2.0.5 on 2018-09-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_descriptive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_description',
        ),
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True, help_text='a description of the quiz', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200, verbose_name='Question_text'),
        ),
    ]
