# Generated by Django 2.1.1 on 2018-10-02 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20181002_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score_rate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Comment')),
            ],
        ),
    ]
