# Generated by Django 2.1.1 on 2018-10-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20181009_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='choice',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
